name: ansi_modifier

description: Style strings for terminal output by adding, replacing, or removing
  ANSI modifiers. Provides support for moving the current cursor position.

version: 0.1.3

homepage: https://github.com/simphotonics/ansi_modifier

topics:
  - ansi
  - terminal
  - console
  - color
  - cursor-position

environment:
  sdk: '^3.0.0'

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
