name: ansi_modifier

description: Style strings for terminal output by
        adding, replacing, or removing ANSI modifiers.

version: 0.1.0

homepage: https://github.com/simphotonics/ansi_modifier

topics:
  - ansi
  - terminal
  - console

environment:
  sdk: '^3.0.0'

dependencies:

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
