name: ansi_modifier

description: Helps styling terminal outputs by adding,
             replacing, and clearing ANSI modifiers.

version: 0.1.5

homepage: https://github.com/simphotonics/ansi_modifier

topics:
  - ansi
  - terminal
  - console
  - color
  - cursor-position

environment:
  sdk: '^3.9.0'

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
